dualidadeapp/apps/teams/urls.py
from django.urls import path
from . import views

app_name = 'teams'

urlpatterns = [
    path('', views.list_teams, name='list_teams'),
    path('adicionar/', views.add_team, name='add_team'),
    path('editar/<int:id_team>/', views.edit_team, name='edit_team'),
    path('excluir/<int:id_team>/', views.delete_team, name='delete_team'),
]

dualidadeapp/dualidadeapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('perfis/', include('profiles.urls', namespace='profiles')),
    path('contas/', include('accounts.urls', namespace='accounts')),
    path('times/', include('teams.urls', namespace='teams')),
    path('demandas/', include('demands.urls', namespace='demands')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dualidadeapp/apps/teams/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Team(models.Model):
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    name = models.CharField('Nome', max_length=50)
    owner = models.ForeignKey(User, related_name='%(class)s_requests_created', on_delete=models.CASCADE)
    user = models.ManyToManyField(User, through='UserTeam', blank=True)
    
    class Meta:
        verbose_name = 'Time'
        verbose_name_plural = 'Times'
        ordering =['id']

    def __str__(self):
        return self.name


class UserTeam(models.Model):
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Usuário de Time'
        verbose_name_plural = 'Usuários de Time'
        ordering =['id']

    def __str__(self):
        return self.team.name

dualidadeapp/apps/teams/forms.py
from django import forms
from .models import Team

class TeamForm(forms.ModelForm):

    class Meta:
        model = Team
        exclude = ('created_on' , 'updated_on',)

dualidadeapp/apps/teams/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import TeamForm
from .models import Team, UserTeam, User

# Create your views here.
def add_team(request):
    template_name = 'teams/add_team.html'
    context = {}
    if request.method == 'POST':
        form = TeamForm(request.POST, request.FILES)
        if form.is_valid():
            f = form.save(commit=False)
            f.save()
            form.save_m2m()
            return redirect('teams:list_teams')
    form = TeamForm()
    context['form'] = form
    return render(request, template_name, context)

def list_teams(request):
    template_name = 'teams/list_teams.html'
    userTeams = UserTeam.objects.filter()
    users = User.objects.filter()
    teams = Team.objects.filter()
    context = {
        'teams': teams,
        'users': users,
        'userTeams': userTeams
    }
    return render(request, template_name, context)

def edit_team(request, id_team):
    template_name = 'teams/add_team.html'
    context ={}
    team = get_object_or_404(Team, id=id_team)
    if request.method == 'POST':
        form = TeamForm(request.POST, request.FILES,  instance=team)
        if form.is_valid():
            form.save()
            return redirect('teams:list_teams')
    form = TeamForm(instance=team)
    context['form'] = form
    return render(request, template_name, context)

def delete_team(request, id_team):
    team = Team.objects.get(id=id_team)
    team.delete()
    return redirect('teams:list_teams')

dualidadeapp/templates/teams/add_team.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}

    Adicionar Time - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
    <h5><b>Cadastro de Time</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <form action="" method="POST"> 
                {% csrf_token %}
                <div class="form-group">
                   <label for="{{ form.name.id_for_label }}">Nome</label>
                   {{ form.name|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.owner.id_for_label }}">Dono</label>
                    {{ form.owner|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.user.id_for_label }}">Usuário</label>
                    {{ form.user|add_class:"form-control" }}
                </div>
                    <button type="submit" class="btn btn-primary">Salvar</button>       
                </form>
            </div>
        </div>
    </div>

{% endblock body %}

dualidadeapp/templates/teams/list_teams.html
{% extends 'base.html' %}

{% block title %}

    Lista de Times - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
        <h5><b>Lista de Times</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <br />
                    <a href="{% url 'teams:add_team' %}">Cadastro de novo time</a>
                <br />
                <br />
                <table class="table table-hover">
                <thead>
                    <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nome</th>
                    <th scope="col">Dono</th>
                    <th scope="col">Integrantes</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for team in teams %}
                        <tr>
                            <th scope="row">{{ team.id }}</th>
                            <td>{{ team.name }}</td>
                            <td>{{ team.owner }}</td>
                            <td>
                                {% for userTeam in userTeams %}
                                    {% if userTeam.team.id == team.id %}
                                        <li>{{ userTeam.user }}</li>
                                    {% endif %}
                                {% endfor %}
                            </td>
                            {% if user.id == team.owner.id %}
                                <td>
                                    <a href="{% url 'teams:edit_team' team.id %}" class="btn btn-primary btn-sm">Editar</a>
                                </td>
                                <td>    
                                    <a href="{% url 'teams:delete_team' team.id %}" class="btn btn-danger btn-sm ">Excluir</a>
                                </td>
                            {% endif %}
                        </tr> 
                    {% endfor %}
                </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock body %}