dualidadeapp/apps/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('novo-usuario/',views.add_user, name='add_user'),
    path('login/',views.user_login, name='user_login'),
    path('sair/',views.user_logout, name='user_logout'),
    path('alterar-senha/',views.user_change_password, name='user_change_password'),
    path('alterar-usuario/<username>/',views.user_change_information, name='user_change_information'),
]

dualidadeapp/apps/demands/urls.py
from django.urls import path
from . import views

app_name = 'demands'

urlpatterns = [
    path('', views.list_demands, name='list_demands'),
    path('adicionar/', views.add_demand, name='add_demand'),
    path('editar/<int:id_demand>/', views.edit_demand, name='edit_demand'),
    path('excluir/<int:id_demand>/', views.delete_demand, name='delete_demand'),
    path('demanda/<int:id_demand>/', views.demand_detail, name='demand_detail'),
    path('demandaInteresse/<int:id_demand>/', views.demand_add_like, name='demand_add_like'),
    path('buscar/', views.search_demands, name='search_demands'),
]

dualidadeapp/apps/profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'

urlpatterns = [
    path('editar/<int:id_user>/', views.edit_profile, name='edit_profile'),
]

dualidadeapp/apps/teams/urls.py
from django.urls import path
from . import views

app_name = 'teams'

urlpatterns = [
    path('', views.list_teams, name='list_teams'),
    path('adicionar/', views.add_team, name='add_team'),
    path('editar/<int:id_team>/', views.edit_team, name='edit_team'),
    path('excluir/<int:id_team>/', views.delete_team, name='delete_team'),
]

dualidadeapp/dualidadeapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('perfis/', include('profiles.urls', namespace='profiles')),
    path('contas/', include('accounts.urls', namespace='accounts')),
    path('times/', include('teams.urls', namespace='teams')),
    path('demandas/', include('demands.urls', namespace='demands')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dualidadeapp/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>{% block title %}Dualidade App{% endblock title %}</title>
</head>
<body>

    <!-- INICIO: Bloco do Bootstrap a ser incluido -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="/">Dualidade App</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample05" aria-controls="navbarsExample05" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarsExample05">
            {% if user.is_authenticated %}
            <ul class="navbar-nav mr-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown05" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Menu</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown05">
                        <a class="dropdown-item" href="{% url 'demands:list_demands' %}">Demandas</a>
                        <a class="dropdown-item" href="{% url 'teams:list_teams' %}">Times</a>
                    </div>
                </li>
            </ul>
            <form action="{% url 'demands:search_demands' %}" method="GET" class="form-inline my-2 my-md-0" style="margin-right: 10px">
                <input class="form-control" name="query" type="text" placeholder="Titulo/desc da demanda" aria-label="Buscar" style="margin-right: 10px">
                <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Buscar</button>
            </form>
            <ul class="navbar-nav">
                <li class="nav-item"> 
                    {% if user.profile.photo %}
                        <img src="{{ user.profile.photo.url }}" class="rounded-circle" width="40" height="40" >
                    {% else %}
                        <img src="{% static 'img/user.png' %}" class="rounded-circle" width="40" height="40" >
                    {% endif %}
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown05" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ user.get_full_name|default:user.username }}</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown05">
                        <a class="dropdown-item" href="{% url 'accounts:user_change_information' user.username %}">Conta</a>
                        <a class="dropdown-item" href="{% url 'profiles:edit_profile' user.id %}">Perfil</a>
                        <a class="dropdown-item" href="{% url 'accounts:user_change_password' %}">Trocar senha</a>
                        <a class="dropdown-item" href="{% url 'accounts:user_logout' %}">Sair</a>
                    </div>
                </li>
            </ul>
            {% else %}
            <a href="{% url 'accounts:user_login' %}">
                <button class="btn btn-outline-secondary my-2 my-sm-0">Logar</button>
            </a> 
            {% endif %}
        </div>
    </nav>
    <!-- FIM: Bloco do Bootstrap a ser incluido -->
    
    {% block body %}
    
    {% endblock body %}
    
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/jquery.mask.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>