dualidadeapp/apps/demands/urls.py
from django.urls import path
from . import views

app_name = 'demands'

urlpatterns = [
    path('', views.list_demands, name='list_demands'),
    path('adicionar/', views.add_demand, name='add_demand'),
    path('editar/<int:id_demand>/', views.edit_demand, name='edit_demand'),
    path('excluir/<int:id_demand>/', views.delete_demand, name='delete_demand'),
    path('demanda/<int:id_demand>/', views.demand_detail, name='demand_detail'),
    path('demandaInteresse/<int:id_demand>/', views.demand_add_like, name='demand_add_like'),
    path('buscar/', views.search_demands, name='search_demands'),
]

dualidadeapp/dualidadeapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('perfis/', include('profiles.urls', namespace='profiles')),
    path('contas/', include('accounts.urls', namespace='accounts')),
    path('times/', include('teams.urls', namespace='teams')),
    path('demandas/', include('demands.urls', namespace='demands')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dualidadeapp/apps/demands/models.py
from django.db import models
from teams.models import Team
from django.contrib.auth.models import User

# Create your models here.
class Demand(models.Model):
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    title = models.CharField('Titulo', max_length=50)
    description = models.TextField('Descricao', max_length=100)
    deadline = models.DateField('Prazo Final', auto_now=False, auto_now_add=False) 
    type = models.CharField('Tipo', max_length=50)
    STATUS_CHOICES = (
        ('Disponível', 'Disponível'),
        ('Em andamento', 'Em andamento'),
        ('Finalizado', 'Finalizado'),
        ('Cancelado', 'Cancelado'),
    )
    status = models.CharField('Status', max_length=20, choices=STATUS_CHOICES, null=True, blank=True, default='Disponível')
    file = models.FileField('Documento', upload_to='docs')
    repository = models.CharField('Repositorio', max_length=100)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.CASCADE, default=None, blank=True, null=True)
    
    class Meta:
        verbose_name = 'Demanda'
        verbose_name_plural = 'Demandas'
        ordering =['id']

    def __str__(self):
        return self.name


class DemandTeamLike(models.Model):
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    demand = models.ForeignKey(Demand, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Like de time em demanda'
        verbose_name_plural = 'Likes de time em demanda'
        ordering =['id']

    def __str__(self):
        return self.team.name

dualidadeapp/apps/demands/forms.py
from django import forms
from .models import Demand, DemandTeamLike

class DemandForm(forms.ModelForm):

    class Meta:
        model = Demand
        exclude = ('created_on' , 'updated_on', 'team', 'status')


class DemandTeamLikeForm(forms.ModelForm):
    
    class Meta:
        model = DemandTeamLike
        exclude = ('created_on' , 'updated_on', 'demand')

dualidadeapp/apps/demands/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import DemandForm, DemandTeamLikeForm
from .models import Demand, DemandTeamLike, Team, User

# Create your views here.
def add_demand(request):
    template_name = 'demands/add_demand.html'
    context = {}
    if request.method == 'POST':
        form = DemandForm(request.POST, request.FILES)
        if form.is_valid():
            f = form.save(commit=False)
            f.status = "Disponível"
            f.save()
            form.save_m2m()
            return redirect('demands:list_demands')
    form = DemandForm()
    context['form'] = form
    return render(request, template_name, context)

def list_demands(request):
    template_name = 'demands/list_demands.html'
    demands = Demand.objects.filter()
    context = {
        'demands': demands
    }
    return render(request, template_name, context)

def demand_detail(request, id_demand):
    template_name = 'demands/demand_detail.html'
    demand = get_object_or_404(Demand, id=id_demand)
    demandTeamLikes = DemandTeamLike.objects.filter()
    context = {
        'demand': demand,
        'demandTeamLikes': demandTeamLikes
    }
    if request.method == "POST":
        team_id = request.POST['accept']
        if team_id:
            team = Team.objects.get(id=int(team_id))
            if team:
                demand.team = team
                demand.status = 'Em andamento'
                demand.save()
                return redirect('demands:list_demands')

    return render(request, template_name, context)
    
def edit_demand(request, id_demand):
    template_name = 'demands/add_demand.html'
    context ={}
    demand = get_object_or_404(Demand, id=id_demand)
    if request.method == 'POST':
        form = DemandForm(request.POST, request.FILES,  instance=demand)
        if form.is_valid():
            form.save()
            return redirect('demands:list_demands')
    form = DemandForm(instance=demand)
    context['form'] = form
    return render(request, template_name, context)
    
def demand_add_like(request, id_demand):
    template_name = 'demands/demand_add_like.html'
    context ={}
    if request.method =='POST':
        form = DemandTeamLikeForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            demand = Demand.objects.get(id=id_demand)
            f.demand = demand
            f.save()
            form.save_m2m()
            return redirect('demands:list_demands')
    form = DemandTeamLikeForm()
    context['form'] = form

    return render(request, template_name, context)

def delete_demand(request, id_demand):
    demand = Demand.objects.get(id=id_demand)
    demand.delete()
    return redirect('demands:list_demands')

def search_demands(request):
    template_name = 'demands/list_demands.html'
    query = request.GET.get('query')
    demands = Demand.objects.filter(title__icontains=query) | Demand.objects.filter(description__icontains=query)
    context = {
        'demands': demands,
    }
    return render(request,template_name, context)

dualidadeapp/templates/demands/add_demand.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}

    Adicionar Demanda - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
    <h5><b>Cadastro de Demanda</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <form action="" method="POST" enctype="multipart/form-data"> 
                {% csrf_token %}
                <div class="form-group">
                   <label for="{{ form.title.id_for_label }}">Titulo</label>
                   {{ form.title|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.description.id_for_label }}">Descricao</label>
                    {{ form.description|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.deadline.id_for_label }}">Prazo final</label>
                    {{ form.deadline|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.type.id_for_label }}">Tipo</label>
                    {{ form.type|add_class:"form-control" }}
                </div>
                <!-- <div class="form-group">
                    <label for="{{ form.status.id_for_label }}">Status</label>
                    {{ form.status|add_class:"form-control" }}
                </div> -->
                <div class="form-group">
                    <label for="{{ form.file.id_for_label }}">Documento</label>
                    {{ form.file|add_class:"form-control-file" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.repository.id_for_label }}">Repositorio</label>
                    {{ form.repository|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.owner.id_for_label }}">Dono</label>
                    {{ form.owner|add_class:"form-control" }}
                </div>
                <!-- <div class="form-group">
                    <label for="{{ form.team.id_for_label }}">Time</label>
                    {{ form.team|add_class:"form-control" }}
                </div> -->
                    <button type="submit" class="btn btn-primary">Salvar</button>       
                </form>
            </div>
        </div>
    </div>

{% endblock body %}

dualidadeapp/templates/demands/demand_add_like.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}

    Demonstrar Interesse - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
    <h5><b>Demonstrar Interesse</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <form action="" method="POST"> 
                    {% csrf_token %}
                    <p>Deseja demonstrar interesse com qual time?</p>
                    <div class="form-group">
                        <label for="{{ form.team.id_for_label }}">Time</label>
                        {{ form.team|add_class:"form-control" }}
                    </div>
                    <button type="submit" class="btn btn-primary">Salvar</button>       
                </form>
            </div>
        </div>
    </div>

{% endblock body %}

dualidadeapp/templates/demands/demand_detail.html
{% extends 'base.html' %}

{% load static %}

{% load widget_tweaks %}


{% block blockname %}
    Detalhe da Demanda - {{ block.super }}
{% endblock blockname %}


{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
            <br />
            <h1>Detalhe da Demanda</h1>
            <br />
            <div class="media">
                <img src="{{ demand.file.url }}" class="align-self-start mr-3 rounded-circle" width="100" height="100">
                <div class="media-body">
                    <h5 class="mt-0">{{ demand.title }}</h5>
                    <p>Descrição: {{ demand.description }}</p>
                    <p>Prazo Final: {{ demand.deadline }}</p>
                    <p>Status: {{ demand.status }}</p>
                    <p>Dono: {{ demand.owner }}</p>
                    <p>Time: {{ demand.team }}</p>
                </div>
            </div>
            <br />
            {% if demand.status == "Disponível" %}
                <h3>Interessados</h2>
                    {% if user.id != demand.owner.id %}
                        <td>
                            <a href="{% url 'demands:demand_add_like' demand.id %}" class="btn btn-primary btn-sm">Demonstrar interesse</a>
                        </td>
                        <br />
                        <br />   
                    {% endif %}
                <table class="table table-hover">
                    <thead>
                        <tr>
                        <th scope="col">#</th>
                        <th scope="col">Time</th>
                        <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for demandTeamLike in demandTeamLikes %}
                            {% if demandTeamLike.demand.id == demand.id %}
                            <tr>
                                <th scope="row">{{ demandTeamLike.id }}</th>  
                                <td>{{ demandTeamLike.team.name }}</td>
                                {% if user.id == demand.owner.id %}
                                    <td>
                                        <form action="" method="POST">
                                            {% csrf_token %}
                                            <button 
                                                type="submit" 
                                                class="btn btn-primary btn-sm"
                                                value="{{ demandTeamLike.team.id }}" 
                                                name="accept">Aceitar
                                            </button>
                                        </form>
                                        
                                    </td> 
                                {% endif %}
                            </tr> 
                            {% endif %}
                        {% endfor %}  
                    </tbody>
                </table>
            {% endif %}
        </div>
    </div>
{% endblock body %}

dualidadeapp/templates/demands/list_demands.html
{% extends 'base.html' %}

{% block title %}

    Lista de Demandas - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
        <h5><b>Lista de Demandas</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <br />
                    <a href="{% url 'demands:add_demand' %}">Cadastro de nova demanda</a>
                <br />
                <br />
                <table class="table table-hover">
                <thead>
                    <tr>
                    <th scope="col">#</th>
                    <th scope="col">Titulo</th>
                    <th scope="col">Descricao</th>
                    <th scope="col">Prazo Final</th>
                    <th scope="col">Tipo</th>
                    <th scope="col">Status</th>
                    <th scope="col">Repositorio</th>
                    <th scope="col">Dono</th>
                    <th scope="col">Time</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for demand in demands %}
                        <tr>
                            <th scope="row">{{ demand.id }}</th>       
                            <td>{{ demand.title }}</td>
                            <td>{{ demand.description }}</td>
                            <td>{{ demand.deadline }}</td>
                            <td>{{ demand.type }}</td>
                            <td>{{ demand.status }}</td>
                            <td>{{ demand.repository }}</td>
                            <td>{{ demand.owner }}</td>
                            <td>{{ demand.team }}</td>
                            <td>
                                <a href="{% url 'demands:demand_detail' demand.id %}" class="btn btn-primary btn-sm">Detalhes</a>
                            </td>
                            {% if user.id == demand.owner.id %}
                                <td>
                                    <a href="{% url 'demands:edit_demand' demand.id %}" class="btn btn-primary btn-sm">Editar</a>
                                </td>
                                <td>    
                                    <a href="{% url 'demands:delete_demand' demand.id %}" class="btn btn-danger btn-sm ">Excluir</a>
                                </td>   
                            {% endif %}
                        </tr> 
                    {% endfor %}
                </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock body %}